version: '3.8'

services:
  # Aplicación Frontend
  hr-platform:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:3001/api
    depends_on:
      - api
    networks:
      - hr-network
    restart: unless-stopped

  # API Backend (simulado)
  api:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./api-mock:/usr/share/nginx/html
      - ./api-nginx.conf:/etc/nginx/nginx.conf
    networks:
      - hr-network
    restart: unless-stopped

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - hr-network
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

  # PostgreSQL para datos persistentes (opcional)
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=hr_platform
      - POSTGRES_USER=hr_user
      - POSTGRES_PASSWORD=hr_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - hr-network
    restart: unless-stopped

networks:
  hr-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local